//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curs3laba4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Readers
    {
        public int r_id { get; set; }
        public string r_fio { get; set; }
        public Nullable<System.DateTime> r_dt_birth { get; set; }
        public string r_passport { get; set; }
    }
}
